anypoint:
  api:
    id: "18961598"
  app:
    clientId: "xxxxx"
    clientSecret: "yyyyy"
  businessGroup: "ae6d7954-6fc2-4f3e-8777-80ff8aabd859"
  portal:
    assetId: anypoint-race-api
    version: "2.0.1"
    timeout: "20000"
    pages:
      results:
        firstToFinish: "90u-n91/Results: First to Finish"
        fastest: "5sl-367/Results: Fastest"
        most: "vjf-28f/Results: Perseverance"
        halloffame: "qz7-40n/Hall of Fame"
        easterEgg: "cr0-6ca/Results: 2023 Mystery"
racedata:
# will work once we deploy to a private space. Will not work in shared space
#  host: race-data-sapi
#  port: "8081"
#  protocol: HTTP
  host: ???????.usa-e2.cloudhub.io
  port: "443"
  protocol: HTTPS
  path: /api
  
redis:
  host: redis-18615.c1.us-east1-2.gce.cloud.redislabs.com
  port: "18615"

race:
  expiry: "259200" # seconds
      