http:
  port: "8081"
  
anypoint:
  api:
    id: "20093051"
  businessGroup: "3ab0f923-8bcb-4e7b-aa6e-0b984a18c811"
  portal:
    assetId: anypoint-race-api
    version: "4.0.0"
    timeout: "20000"

referee:
  host: referee-papi
  port: "8081"
  protocol: HTTP
  path: /api
          
racedata:
  host: race-data-sapi
  port: "8081"
  protocol: HTTP
  path: /api

racerdata:
  host: beyond-test.anypointspeedway.com
  port: "443"
  protocol: HTTPS
  path: /racerdata-sapi

race:
  expiry: "7200" # seconds

practice:
  expiry: "7200" # seconds