anypoint:
  app:
    clientId: "bf857b9be7864cb5a98c3e89ae8c9bf6"
    clientSecret: "64Fb288641994BBd86E4538000958856"
  businessGroup: "b507dcaa-0d5b-42e9-9446-97b82d7bf81e"
  portal:
    assetId: anypoint-race-api
    version: "1.1.1"
    pages:
      results:
        firstToFinish: "yhd-zsf/Results: First to Finish"
        fastest: "ezc-wes/Results: Fastest"
        most: "f1l-f5o/Results: Perseverance"
        halloffame: "ihl-aks/Hall of Fame"  
    
      