anypoint:
  api:
    id: "19105319"
  businessGroup: "3ab0f923-8bcb-4e7b-aa6e-0b984a18c811"
  portal:
    assetId: anypoint-race-api
    version: "2.0.0"
    timeout: "20000"
    pages:
      results:
        firstToFinish: "7aq-sjs/Results: First to Finish"
        fastest: "0t1-29r/Results: Fastest"
        most: "99i-oc0/Results: Perseverance"
        halloffame: "5ip-grn/Hall of Fame"
        easterEgg: "dla-n7g/Results: Easter Egg"
        
racedata:
  host: race-data-sapi
  port: "8081"
  protocol: HTTP
  path: /s/race-data
  
redis:
  host: redis-15552.c1.us-east1-2.gce.cloud.redislabs.com
  port: "15552"

race:
  expiry: "600" # seconds

practice:
  expiry: "600" # seconds