anypoint:
  api:
    id: "18871097"
  app:
    clientId: "xxxxx"
    clientSecret: "yyyyy"
  businessGroup: "ae6d7954-6fc2-4f3e-8777-80ff8aabd859"
  portal:
    assetId: anypoint-race-api
    version: "1.0.0"
    timeout: "20000"
    pages:
      results:
        firstToFinish: "90u-n91/Results: First to Finish"
        fastest: "5sl-367/Results: Fastest"
        most: "vjf-28f/Results: Perseverance"
        halloffame: "qz7-40n/Hall of Fame"  
    
      